# ~/.config/yazi/keymap.toml

[mgr]
prepend_keymap = [
  { on = [ "g", "h" ], run = 'cd ~', desc = "Go to home" },
  { on = [ "g", "w" ], run = 'cd ~/workspace', desc = "Go to workspace" },
  { on = [ "g", "c" ], run = 'cd ~/.config', desc = "Go to ~/.config" },
  { on = [ "!" ], run = 'shell "$SHELL" --block --confirm', desc = "Open shell here" },
  { on = [ "e" ], run = 'open --interactive', desc = "Open interactively" },
  { on = [ "y", "p" ], run = 'copy path', desc = "Copy file path" },
  { on = [ "y", "n" ], run = 'copy filename', desc = "Copy filename" },
  { on = [ "R" ], run = 'refresh', desc = "Refresh" },
]
